<template>
  <div class="wrapper">
    <div class="gridWrapper">
      <div class="navbarWrapper">
        <Navbar />
      </div>
      <main>
        <div class="card-list">
          <h2>首頁</h2>
          <UserCreateTweet @after-create-tweet="afterCreateTweet" />
          <Tweet v-for="tweet in tweets" :key="tweet.id" :initTweet="tweet"/>
        </div>
      </main>
      <div class="popularList">
        <PopularUser />
      </div>
    </div>
  </div>
</template>

<script>
import Navbar from "../components/Navbar.vue";
import Tweet from "../components/Tweet.vue";
import PopularUser from "../components/PopularUser.vue";
import UserCreateTweet from "../components/UserCreateTweet.vue";

const dummyUser = {
    id: 1,
    email: "root@example.com",
    password: "12345678",
    name: "root",
    account: "root",
    role: "admin",
    avatar: "https://gravatar.com/avatar/992ba14216a3e429e1b6c3bd498cfabe?s=400&d=wavatar&r=x",
    introduction: "",
    cover: "",
    tweetCount: null,
    followingCount: null,
    followerCount: null,
    likedCount: null,
    createdAt: "",
    updatedAt: "",
  }
const dummyData = [
  {
    id: 4,
    UserId: 4,
    description:
      "Et veniam tempore impedit eos dolorem veritatis voluptas. Neque expedita doloribus autem recusandae asperiores et ex officiis. Mollitia quam animi et tempora velit aut possimus. Voluptas dolores explicabo labore consequatur voluptas voluptatibus. Aut voluptates est vero voluptatem adipisci et nostrum accusantium.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 14,
    UserId: 4,
    description:
      "Distinctio quaerat in consequatur libero dolores quas assumenda accusamus. Et et itaque sed explicabo quasi repellendus. Quo magnam qui aut accusamus dolor qui odio placeat quidem. Et recusandae aperiam et numquam tempora amet recusandae. Voluptate autem a aliquam culpa nam sed sit quaerat perspiciatis.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 24,
    UserId: 4,
    description:
      "Amet veniam alias deleniti ullam vel eius sunt dolorum esse. Doloribus qui ratione nobis quis debitis aut enim amet. Ut mollitia est quia beatae error laudantium. Eos est voluptatem et autem rerum itaque sit reiciendis fugiat. Sed provident eos reiciendis reprehenderit illo voluptatem veritatis omnis. Voluptatem et perspiciatis dolorem quia iste occaecati.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 34,
    UserId: 4,
    description: "Iusto occaecati aliquam sed.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 44,
    UserId: 4,
    description: "Iusto non debitis placeat est dolore ut eos.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 54,
    UserId: 4,
    description: "aliquam",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 64,
    UserId: 4,
    description: "dicta nisi vero",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 74,
    UserId: 4,
    description:
      "Laboriosam nobis quae omnis ipsum voluptas porro reprehenderit. Aliquam non alias ab repudiandae et ut. Omnis repellendus quo eum dolorem voluptatem tempore est. Adipisci autem quibusdam consequatur minus. Nulla repudiandae placeat repellendus magnam quidem ab vel sed quibusdam. Et enim aspernatur ut maxime nesciunt provident.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 84,
    UserId: 4,
    description:
      "Deserunt atque voluptatibus id voluptatem. Sint veritatis praesentium est et sed natus quia eligendi. Exercitationem enim quidem tempora voluptatem. A quae quos dolorem dicta illum soluta. Ea minima vero. Cum quasi ut accusamus non aut voluptatem.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 94,
    UserId: 4,
    description:
      "Deserunt quia eveniet eveniet facilis nihil ut quia quibusdam.\nQui id aut laudantium modi error explicabo quia nisi.\nAb temporibus necessitatibus quia et praesentium excepturi sint dolores mollitia.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 4,
    User: {
      id: 4,
      email: "root@example.com",
      password: "$2a$10$IcKYCk0dT7T/2ctcxtOBhOdy49j6ZvZONNKqLARRUMXr7XMusSDD.",
      name: "root",
      account: "root",
      role: "admin",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "Dicta voluptas velit aut.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 104,
    UserId: 14,
    description:
      "Molestiae minus ullam. Iure distinctio minima eos eaque corporis vero perferendis quos velit. Facere et sed porro. Impedit aut quaerat.\n \rVoluptas occaecati adipisci non vero ad incidunt illo. Deleniti nisi accusantium modi amet excepturi libero neque. Sit quis dolorem reiciendis voluptatum. Ut modi id velit nobis et. Iure necessitatibus facilis.\n \rAtque magni accusantium velit dolorem necessitatibus iste facere. Quis rerum explicabo quia cum esse. Sunt sit rerum laudantium. Molestiae quo rerum. Provident deleniti qui neque alias.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 114,
    UserId: 14,
    description: "rem",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 124,
    UserId: 14,
    description: "ut",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 134,
    UserId: 14,
    description:
      "Neque rerum laborum vel accusantium occaecati molestiae alias mollitia ullam.\nAmet veritatis quae quis modi autem incidunt quis dolore.\nArchitecto ipsa culpa.\nVoluptatem sed aut quaerat voluptatibus sint esse aut autem.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 144,
    UserId: 14,
    description:
      "Molestias est amet quas amet quibusdam ratione expedita est. Sed occaecati temporibus in accusamus libero magni. Quia laborum et ut amet rerum ea sit. Sunt consequuntur quo. Dolor sed beatae perspiciatis nostrum iste culpa totam. Atque delectus aut blanditiis adipisci molestias ut.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 154,
    UserId: 14,
    description:
      "Quia sint itaque fugiat autem et dolor velit. Sunt dolores veniam. Corporis laborum illo facere. Beatae harum minima et rerum cumque quis non amet.\n \rEst aut cumque veritatis. Molestias sequi illo praesentium. Et ullam id cupiditate pariatur at ut velit aut ut.\n \rAut blanditiis laborum cum voluptatibus esse illo aliquid. Est vel qui culpa a dignissimos omnis tempora architecto. Repudiandae illo consequatur ipsam impedit voluptatem eum qui. Qui distinctio explicabo inventore necessitatibus in voluptatem ut quia placeat.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 164,
    UserId: 14,
    description:
      "Expedita sed sit repudiandae facilis accusantium vero debitis sit eligendi. Et qui beatae repudiandae veritatis voluptates. Laborum nisi ut ducimus.\n \rVeritatis facere maiores quos veniam sit praesentium. Illo sapiente repellat recusandae voluptas sed. Minus temporibus et velit accusantium saepe provident. Maiores est aut occaecati voluptates architecto fuga quod aut voluptatem.\n \rMinus sed voluptatum. Optio fugit ut architecto. Quae possimus quas ut. Sequi et provident vel nihil. Voluptatum doloribus esse consectetur voluptatum pariatur iusto possimus laborum aut.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 174,
    UserId: 14,
    description: "ex",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 184,
    UserId: 14,
    description: "Laborum nihil quia et soluta.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 194,
    UserId: 14,
    description:
      "Voluptatibus est soluta. Nulla autem voluptatibus. Cum maxime amet iure laboriosam quas saepe voluptatibus quas praesentium. Iusto quia dolorum aliquid occaecati quia.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 14,
    User: {
      id: 14,
      email: "user1@example.com",
      password: "$2a$10$Ash3UVrVeR7biBifak/IDemhNCagTdsnZNc8C0zqDezbDtTJ.oWsC",
      name: "Darla Adams",
      account: "user1",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Mollitia harum est dicta dolorem aut.\nQuae aut est quisquam ratione rem vel.\nRerum omnis dolorem possimus ut facere ut culpa in.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:21.000Z",
      updatedAt: "2022-02-25T15:41:21.000Z",
    },
  },
  {
    id: 204,
    UserId: 24,
    description: "quia",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 214,
    UserId: 24,
    description: "dolores et velit",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 224,
    UserId: 24,
    description:
      "Velit suscipit voluptas qui ut.\nMolestiae et omnis.\nAut consequatur dicta eveniet distinctio.\nDolorem qui delectus id.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 234,
    UserId: 24,
    description:
      "Ea fugiat dolores dicta modi aliquam molestiae. Sit delectus ea quia rerum enim quo architecto rem. Eaque quis reiciendis est maxime omnis.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 244,
    UserId: 24,
    description: "quibusdam rerum voluptas",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 254,
    UserId: 24,
    description:
      "Nihil quibusdam porro excepturi quibusdam nostrum velit quo. Autem autem nihil autem magnam voluptas recusandae mollitia veniam.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 264,
    UserId: 24,
    description: "exercitationem",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 274,
    UserId: 24,
    description:
      "Cumque neque totam dolores itaque.\nEaque quia corporis sunt nihil veniam modi voluptatem.\nCommodi aperiam et eveniet deleniti quisquam.\nExplicabo quia suscipit in laudantium.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 284,
    UserId: 24,
    description:
      "Atque necessitatibus voluptatem iusto. Earum doloremque nostrum vitae rerum numquam ducimus molestias. Ratione vel eos autem harum maxime quo autem veniam.\n \rModi rem magnam. Ut exercitationem alias ut corrupti autem voluptatem eos sed ipsam. Aspernatur hic ducimus non. Illum delectus sit eos quibusdam sapiente voluptatem dolorem ad aspernatur. Aperiam est molestiae. Omnis omnis non officiis et et quibusdam tenetur quod.\n \rNon doloremque ipsam et odio possimus officia accusantium quis dolores. Deleniti praesentium aut provident necessitatibus ipsum modi minima vel. Earum nam quidem. Laudantium omnis ea dolorum aut sed doloremque ipsa eum atque. Sed maxime quod.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 294,
    UserId: 24,
    description:
      "Hic rerum velit dolorem nam quos assumenda nam. Nam accusantium animi. Ad numquam soluta enim necessitatibus minus rerum. Tempore rerum autem voluptates placeat rem voluptatem.\n \rAdipisci sunt aut veniam suscipit iure. Quaerat iste hic nemo quos ratione et. Placeat possimus suscipit praesentium eos quia ea. Voluptatibus nesciunt architecto quo aut fugiat ullam. Et accusamus delectus aliquid tempore ipsa tenetur et sunt. Odit consequatur quaerat omnis sunt nemo alias.\n \rAccusantium non ut accusantium cum hic ad perferendis. Blanditiis ex rerum qui voluptatibus est voluptatem. Provident temporibus cupiditate. Quo consequatur consequatur consequatur pariatur sed. Fuga omnis est et ullam qui. Rerum aliquid facilis sit ipsam consequuntur minima dolorem et natus.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 24,
    User: {
      id: 24,
      email: "user2@example.com",
      password: "$2a$10$17rgTL6kuOU4tXVqT4pHleNhSJ43vBb7M9i9n6S3mgWvNpbE4M5CW",
      name: "Erma Hand MD",
      account: "user2",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Soluta illum sapiente quia et recusandae velit. Quia dolores et placeat voluptas rerum velit molestiae quo. Enim ex quis.",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 304,
    UserId: 34,
    description:
      "Delectus pariatur in qui aut perspiciatis odio. Nulla explicabo aliquam ipsa eum reiciendis atque. Neque dolorum sapiente quis est sed est. Molestiae odio aut repudiandae beatae.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 314,
    UserId: 34,
    description: "dolores",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 324,
    UserId: 34,
    description:
      "Et voluptates praesentium quod ut et ea expedita.\nAutem qui ipsam deserunt vero.\nQuia eius sequi dolor at est facere deserunt maiores omnis.\nSit rerum reiciendis pariatur incidunt repellendus.\nEx consequatur labore fugiat delectus rem nesciunt tempore necessitatibus.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 334,
    UserId: 34,
    description:
      "Explicabo dolorem ex qui voluptatibus esse eveniet deleniti esse. Optio velit et. Nam harum amet aliquam molestiae qui.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 344,
    UserId: 34,
    description:
      "Ratione architecto maiores voluptatum. Quae nihil ut est aperiam eius ducimus odio id. Deleniti ipsam aliquam enim neque asperiores aliquid impedit nihil nulla.\n \rIllo in facere voluptas in at eaque pariatur perspiciatis veniam. Cumque perspiciatis optio. Adipisci nihil rerum eos est dolorum quia.\n \rVoluptatem qui et voluptatem quia dolores cumque doloribus quas illo. Harum quo corporis deserunt nihil ut quo a. Ut quae sed sed eos voluptatibus. Ullam provident iusto magnam labore.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 354,
    UserId: 34,
    description:
      "Sit voluptatem eligendi. Molestiae provident nemo tenetur facilis qui. Velit ab rerum quae vel totam ullam consectetur magni vitae. Ex et iure qui veniam magni ut.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 364,
    UserId: 34,
    description:
      "Voluptatem fuga velit.\nConsequuntur ad voluptate.\nAccusamus aliquam aut qui.\nCumque labore corrupti.\nIn quisquam voluptatibus.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 374,
    UserId: 34,
    description: "voluptate nesciunt et",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 384,
    UserId: 34,
    description:
      "Quas quas error quo. Quo ratione quaerat. Non eveniet dicta maxime eos rerum quia perspiciatis expedita. Rerum mollitia ut optio amet praesentium. Perferendis nemo voluptates asperiores sint ipsum aut unde voluptatum.\n \rCorporis id aut eius voluptate odio sunt deleniti voluptatem. Et rerum suscipit accusantium impedit ut quaerat. Suscipit incidunt eius quas aut. Delectus odit velit nihil.\n \rNemo adipisci nihil non assumenda quasi ipsam ipsum sint est. Velit enim laudantium consequatur et a officia saepe. Voluptas sapiente omnis magni. Est voluptatem accusamus exercitationem est et neque. Fuga non vero. Dicta labore quod reiciendis accusamus magni porro sed ut.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 394,
    UserId: 34,
    description:
      "Eos voluptate qui molestias consequuntur aut quam voluptatem ea. Reprehenderit non unde deserunt. Tempora voluptatibus ab autem voluptas consectetur provident.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 34,
    User: {
      id: 34,
      email: "user3@example.com",
      password: "$2a$10$fVgHA417Ic7dbvsOk8LEQO5RNPvnyrzlj5n9ocgUYx7EBR2/Q.phO",
      name: "Darren Kuhlman",
      account: "user3",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction: "iure neque ipsum",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 404,
    UserId: 44,
    description: "dignissimos nisi non",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 414,
    UserId: 44,
    description:
      "Excepturi nihil aut temporibus voluptatem dolor similique. Modi excepturi dolor eius aliquid aliquam a ipsam. Perferendis ratione aliquid.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 424,
    UserId: 44,
    description:
      "Provident voluptatem quis. Iusto aliquam aperiam et quia. A culpa animi cum quam.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 434,
    UserId: 44,
    description:
      "Ut enim cupiditate occaecati est voluptatem repudiandae magni. Occaecati incidunt vel eveniet cumque ad voluptatem ipsam possimus. Odit rerum voluptas eveniet nobis nesciunt et sed dolor. Exercitationem rerum corporis animi cum doloribus eius quia facere soluta. Id molestiae quae in sit.\n \rMagni velit saepe iste non magni. Voluptatem esse eligendi nesciunt molestias molestias. Provident necessitatibus nobis sed sed. Rem delectus eveniet. Quisquam debitis voluptatem dolorem maxime quis.\n \rAut voluptates voluptatibus eveniet. Nulla laborum similique. Aliquid natus enim et sit nostrum et exercitationem pariatur vel. Accusantium blanditiis iste quaerat facilis odio consectetur qui cumque in. Eos nemo ut maiores corporis. Assumenda ut molestiae voluptates non et voluptas error distinctio enim.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 444,
    UserId: 44,
    description:
      "In sint molestiae repudiandae dolorum doloribus. Maiores repellendus saepe. Non perspiciatis itaque reprehenderit.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 454,
    UserId: 44,
    description:
      "Incidunt ducimus et. Totam cumque molestiae soluta fuga qui vel rerum temporibus. Nam quia hic eos. Consectetur in corrupti aliquid qui quaerat ut. Quibusdam et sed aut. Quibusdam dicta impedit ea.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 464,
    UserId: 44,
    description:
      "Voluptas id dignissimos quia labore iusto odit dolores veritatis.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 474,
    UserId: 44,
    description:
      "Rerum alias dicta esse occaecati. Ipsam nam consequatur deleniti est labore magni asperiores harum.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 484,
    UserId: 44,
    description:
      "Possimus quis voluptatibus possimus est eos culpa corporis tempora ea.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 494,
    UserId: 44,
    description: "molestias",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 44,
    User: {
      id: 44,
      email: "user4@example.com",
      password: "$2a$10$7JcQbOND21gv.VxzMX2aLeEIUjH0PEp7dUKfpb60PO2PRraDra.Q6",
      name: "Mr. Cathy Konopelski",
      account: "user4",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Dignissimos dolorem ratione est libero molestiae recusandae et voluptas. A ut quis ea. Fugit quia ad dolorum consequatur corporis ut tempore rerum. Modi impedit",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 504,
    UserId: 54,
    description: "Praesentium sed laboriosam in dolorem porro.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 514,
    UserId: 54,
    description:
      "Facilis sit iste iure ab eum veniam harum est.\nAut explicabo eum ut consectetur sit dolorem sed quo.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 524,
    UserId: 54,
    description: "soluta",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 534,
    UserId: 54,
    description:
      "Voluptatem in id aperiam. Eos voluptatem quibusdam nihil natus voluptas eveniet. Veniam commodi et eum modi quam vitae.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 544,
    UserId: 54,
    description:
      "Modi et dolores quas est aspernatur quisquam nulla consequuntur.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 554,
    UserId: 54,
    description:
      "Occaecati labore veniam voluptate odio ut. Veniam in laudantium voluptas et quo debitis voluptatem culpa. Placeat est in vero. Et blanditiis cumque blanditiis repellendus nobis.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 564,
    UserId: 54,
    description: "Nemo possimus incidunt illum.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 574,
    UserId: 54,
    description:
      "Incidunt impedit laudantium. Deleniti harum aut qui. Porro dolore minus distinctio. Sit nulla libero sit quo illo enim aperiam et quia.\n \rLaudantium et consequatur tempora facilis ut est. Eaque enim eaque aut laudantium deserunt sit. Est ducimus voluptatem ut consequatur explicabo numquam. Totam ab repellat nesciunt dolores id. Tenetur minima omnis ratione nostrum suscipit maxime.\n \rEt illum culpa est voluptate esse possimus quidem officia quod. Nobis commodi quod accusantium quisquam nihil mollitia iure. Magnam consequatur et. Ut nisi voluptatem adipisci ut. Alias quia deleniti ut quidem qui. Laboriosam eum ut quibusdam eos necessitatibus.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 584,
    UserId: 54,
    description: "Recusandae at rerum voluptas.",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
  {
    id: 594,
    UserId: 54,
    description: "ea",
    createdAt: "2022-02-25T15:41:22.000Z",
    updatedAt: "2022-02-25T15:41:22.000Z",
    userId: 54,
    User: {
      id: 54,
      email: "user5@example.com",
      password: "$2a$10$TRPwl.k9cNvpxJV1NvM3XujmyTxSH1BBjEZ7.H4QRI9fYajdvDLXK",
      name: "Sherman Heller",
      account: "user5",
      role: "user",
      avatar: "https://loremflickr.com/320/240/people",
      introduction:
        "Quia et quae sint incidunt. Et et enim voluptatum provident est. Occaecati officiis fugiat ad quas reiciendis voluptatum voluptate perferendis ut. Quia est unde",
      cover: "https://loremflickr.com/800/600/paris",
      tweetCount: null,
      followingCount: null,
      followerCount: null,
      likedCount: null,
      createdAt: "2022-02-25T15:41:22.000Z",
      updatedAt: "2022-02-25T15:41:22.000Z",
    },
  },
]
export default {
  name: 'Main',
  components: {
    Navbar,
    UserCreateTweet,
    PopularUser,
    Tweet,
  },
  data() {
    return {
      tweets: []
    };
  },
  methods: {
    afterCreateTweet(payload) {
      const {id, description} = payload
      this.tweets.unshift({
          id,
          UserId: -1,
          description,
          // TODO:優化
          createdAt: new Date(),
          updatedAt: "",
          userId: -1,
          User: {
            id: 4,
            email: dummyUser.email,
            password: dummyUser.password,
            name: "root",
            account: "root",
            role: dummyUser.role,
            avatar: dummyUser.avatar,
            introduction: "",
            cover: "",
            tweetCount: null,
            followingCount: null,
            followerCount: null,
            likedCount: null,
            createdAt: "",
            updatedAt: "",
          }
      }) 
    },
    fetchTeets(){
      this.tweets = dummyData
    }

  },
  created(){
    this.fetchTeets()
  }
};
</script>

<style lang="scss" scoped>
.wrapper {
  .gridWrapper {
    max-width: 1260px;
    margin: 0 auto;
    display: grid;
    grid-template-columns: auto 1fr auto;
    grid-template-rows: auto;
    gap: 30px;
  }
}
.navbarWrapper {
  display: block;
  /* border: 1px solid #000; */
  height: 100%;
  min-height: 100vh;
}
.popularList {
  /* border: 1px solid #000; */
  width: 350px;
  height: 1000px;
}
main {
  background-color: $border;
  width: 100%;
  height: 1200px;
  border: 1px solid $border;
  .card-list {
    > h2 {
      padding: 15px;
      border-bottom: 1px solid $border;
      background-color: $white;
      @include font(18px, 1.4, normal, 700);
    }
  }
}
</style>